research_task:
  description: >
    Conduct thorough research on {company} within the {industry} industry.
    Focus on:
    1. The company's key offerings and products.
    2. The company's strategic focus areas (e.g., market trends, competitive landscape).
    3. The company's market positioning and unique value propositions.
    4. Major industry trends related AI, ML and automation.
  expected_output: >
    A detailed summary document covering the company's key offerings, strategic focus areas,
    and market positioning, along with major industry trends related to AI, ML, and automation.
  agent: researcher

use_case_task:
  description: >
    Based on the research findings, generate a list of 5-7 relevant GenAI, AI, and ML use cases
    that could benefit {company.
    For each use case, provide a clear title, a brief description, the business area it impacts,
    and the potential benefits it could bring to the company.
  expected_output: >
    A list of 5-7 well-defined AI, GenAI, and ML use cases with descriptions, business impact and potential benefits.
  agent: use_case_generator

resource_collection_task:
  description: >
    For each proposed AI use case, identify and collect relevant public datasets, code repositories or open-source projects
    that could be utilized to implement the use cases.
    Focus on high-quality resources from platforms like Kaggle, HuggingFace, and GitHub.
  expected_output: >
    A markdown-formatted list where each item corresponds to a use case and contains clickable links to the resources found.
  agent: resource_collector

feasibility_analysis_task:
  description: >
    For the list of proposed AI use cases, evaluate the technical feasibility and potential risks associated with their implementation at {company}.
    Develop a High-level phased implementation plan for each use case, including:
    1. A summary of key risks and challenges.
    2. High-level phased implementation plan.
    3. Recommendation for a governance framework to ensure ethical and responsible AI use.
  expected_output: >
    A detailed implementation feasibility report for each use case, including risk assessment,
    phased implementation plans, and governance recommendations.
  agent: feasibility_analyst

proposal_writing_task:
  description: >
    Compile the research findings, proposed AI use cases, and collected resources into a comprehensive
    and beautifully formatted final proposal for {company}.
    The proposal should be in markdown format with proper formatting of headings, subheadings, and bullet points.
    The proposal should include the following sections:
    1. An executive summary.
    2. A detailed overview of the company's current market position and industry trends.
    3. A section for each proposed AI use case with descriptions and potential benefits.
    4. A feasibility analysis section summarizing the key findings from the feasibility analysis task.
    5. A resources appendix with links to datasets and code repositories.
  expected_output: >
    A complete, polished and beautifully formatted markdown-formatted technical proposal document ready for presentation.
  agent: proposal_writer